### ISSUE TITLE
Add icons before or after project card showing the type of project

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/ngoako.dev#42]
Types so far:
- Individual
- Group

**Task:**
- [x] Find appropriate svg icons
- [ ] add individual or group(depending on type of project*) from `./src/svgs.js` to `/src/components/Project.js`
- [ ] #54

*the type should be a field in the fetched project object

**Mockups/example**
Styles
```
color: hsl(210,13,71);
```
Larger screens
![image](https://user-images.githubusercontent.com/54069197/161842311-319414db-49ca-424f-86fe-65cb2f309ed2.png)
Smaller screens
![image](https://user-images.githubusercontent.com/54069197/161842529-295a68d4-192d-4b0f-8828-4cfbc227dcde.png)

Also incorporate a Tippyjs tooltip with text "individual project" or "group project". See contact options in navigation component to see how to it's already done.

**Comment by ramachandranram26** [comment]
Hi @Ngoakor12 I have completed this task like the following screen shots
![image](https://user-images.githubusercontent.com/55104665/162195107-e38f0c4f-e54f-43e9-aa96-7760a5878ed7.png)
![image](https://user-images.githubusercontent.com/55104665/162195119-0e29d0e8-2e7a-4be4-a077-671122e23db8.png)
We get the type key from the API ryt ? 
![image](https://user-images.githubusercontent.com/55104665/162195650-3528812d-a576-45f7-8fc6-1e3986a76c9c.png)
is this approach is it okay ?

**Comment by Ngoakor12** [comment]
You're on a roll😅 It looks perfect.
I'll have to jump in the code and verify, but do open a PR and we'll go from there.

**Comment by Ngoakor12** [comment]
I just realised that I haven't added a type field to sanity yet. Let me do that now.

**Comment by Ngoakor12** [comment]
@ramachandranram26 Done adding a type field. You can continue working on this if you want.

**Comment by ramachandranram26** [comment]
Okay @Ngoakor12 I am working on that,  I will create the PR for this issue another 15 mins
