### ISSUE TITLE
add hidden buttons to skip sections

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/ngoako.dev#44]
More context can be found [here](https://www.youtube.com/watch?v=jDDaOFr9nqQ)

Tasks
--
- [x] #58
- [x] #59

**Comment by AjuSingh** [comment]
#### Hi I added the skip navigation button in your project. I cloned your project into my pc but i don't know how to push that code or merge that code into your repository. Guide me to do that thanks.

**Comment by Ngoakor12** [comment]
Hey, thanks for trying to contribute. If all you did was to clone and make changes then all you need to do is follow these steps from me to try and merge your changes:

**1. move your changes to a separate branch using this command**:
`git checkout -b skip-to-main-content-button`
**2. stage and commit your changes**
`git add .`
`git commit -m "added skip to main content button"`
**3. git push**
`git push`
**4. visit the original project repo and you'll see a prompt to open a pull request and I'll have a look**

Please include a screenshot if you can

**Comment by AjuSingh** [comment]
I am not be able to push because of this error:
fatal: The current branch skip-to-main-content-button has no upstream branch.
To push the current branch and set the remote as upstream, use
  git push --set-upstream origin skip-to-main-content-button

**Comment by Ngoakor12** [comment]
This should work:
`git push -u origin skip-to-main-content-button`
