### ISSUE TITLE
Fix overflowing technologies used list on project card

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/ngoako.dev#47]
On small screens, the list of tech used overflows:
![Screenshot_20220406-102327_Chrome](https://user-images.githubusercontent.com/54069197/161931095-1a7d8a71-f4cd-486c-b381-a843e1ccf930.jpg)

I think this applied to the technologies used container should fix the issue:
`flex-wrap: wrap;`

**Comment by ramachandranram26** [comment]
Yes @Ngoakor12  this issue is fixed to using the flex-wrap: wrap technologies container
![image](https://user-images.githubusercontent.com/55104665/162150132-81bb24a1-7ff8-422e-bb98-0523bc96e331.png)
