### ISSUE TITLE
feat: add a hidden "skip projects" button to skip the list of featured projects

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/ngoako.dev#59]
More context can be found [**here**](https://www.youtube.com/watch?v=jDDaOFr9nqQ).

The button should follow the website's **secondary button** style(dig in `./src/App.css` file to find them) plus have a white background. Button style to follow: 
![image](https://user-images.githubusercontent.com/54069197/163594961-50efcc62-5953-47fc-ab98-a6e54d4d3d75.png)

**Comment by rbondoc96** [comment]
Hi there! I'm interested in working on this issue. May I contribute?

**Comment by Ngoakor12** [comment]
Sure, go ahead. Let me know if you need clarity on anything.

**Comment by Ngoakor12** [comment]
Great questions

1. left aligned, so it should line up with the "home" nav item and just below the horizontal line separation the hero section and project section. In other words **top left of projects section**
2. How many tabs shouldn't matter since the above tab navigate(able) items are bound to change. **It should appear right after the _"get in touch"_ button and before _"view more on my github"_ link**
3. A simple **fade in animation or no animation** should be fine
