### ISSUE TITLE
add custom form validation logic function

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/ngoako.dev#60]
Validation logic

All fields:
- Should not be empty

Valid name:
- should be made up of alphanumeric characters

Valid email:
- should start with non-numeric characters
- should include at least one dot(.) character
- should include exactly one at(@) character

**Comment by ThePiyushAggarwal** [comment]
Hey @Ngoakor12 

I would like to work on this issue.

I am thinking of adding some error message just below the input fields and the field will have a red border as well. I have heard about React Hook form. I would like to check it out and use it here.

Please let me know if you have any other requirements. We are going to use this validation in the "Get In Touch" section only right?

**Comment by Ngoakor12** [comment]
I've heard good things about react hook form.

It does sound like you'll be working on the visuals as well, so the main issue to work on is [this one](https://github.com/Ngoakor12/ngoako.dev/issues/7)

Go ahead, let me know if you have further questions.

**Comment by ThePiyushAggarwal** [comment]
Hey @Ngoakor12 

Can I install `axios`? I am unable to properly use the formspree with fetch API.
Earlier the form was submitting using the action attribute but that is not possible if we use React Hook Form.
We need to use an onSubmit handler. In that handler, I need to axios because I am unable to make fetch API work right.

**Comment by Ngoakor12** [comment]
If it helps, sure :+1: 

I haven't touched that part of the code in a long time

**Comment by ThePiyushAggarwal** [comment]
@Ngoakor12 I have raised a PR for this issue.

I know you mentioned issue #7 , but I couldn't understand the difference between these issues exactly.

Please let me know what I missed and if you need any improvements.

**Comment by Ngoakor12** [comment]
> @Ngoakor12 I have raised a PR for this issue.
> 
> I know you mentioned issue #7 , but I couldn't understand the difference between these issues exactly.
> 
> Please let me know what I missed and if you need any improvements.
> 
> Sorry for using up your `formspree` requests. smiling_face_with_tear

No problem, I'll have a look at it soon. Thanks for seeing it through :smiley: 

This and the other issue are very close so don't worry about it.
