### ISSUE TITLE
Add custom form validation

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/ngoako.dev#7]
I don't like the default html validation you get with adding a required attribute to form fields. To complete this issue, I need to:
- [x] #60
- [ ] #61

**Comment by alireza-jahandoost** [comment]
You mean front end validation?

**Comment by Ngoakor12** [comment]
Yes. But this one needs a bit of fleshing out further. I have to come up
with the logic and mockups, then perhaps you can work on it if you like.

**Comment by alireza-jahandoost** [comment]
OK
