### ISSUE TITLE
Navigation bar not showing correctly on mobile

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/ngoako.dev#73]
See chrome screenshot for when I try a scroll down:
![Screenshot_20221008-055416_Chrome.jpg](https://user-images.githubusercontent.com/54069197/194687062-e95814e5-ffbd-4cd6-a5dc-77b2903e81ba.jpg)

The nav bar gets cut at the top but it shouldn't. I suspect it's because of the use of the `fixed` CSS property on chrome mobile. Maybe using sticky instead might solve it, I'm not sure. Poke around and see if you can't figure it out.

**Comment by Ngoakor12** [comment]
Fixed by @Jimmy-Taravia2001 on #74

**Comment by Jimmy-Taravia2001** [comment]
You're welcome. :-)
