### ISSUE TITLE
Migrate from @sanity/block-content-to-react to @portabletext/react

### ISSUE THREAD

**Issue by Ngoakor12** [Ngoakor12/ngoako.dev#92]
https://github.com/portabletext/react-portabletext/blob/main/MIGRATING.md

**Comment by ThePiyushAggarwal** [comment]
Hello @Ngoakor12 

Would you like me to work on this?
I will like to complete this by end of the week.

**Comment by Ngoakor12** [comment]
Sure @ThePiyushAggarwal
